trigger: none
pr: none

variables:
- group: acr-variable-group
- group: aks-variable-group
- template: /common/cd-vars.yaml
  parameters:
      projectName: go-template-1

resources: 
  pipelines:
  - pipeline: ci
    source: "go-template-1-ci"
    trigger:
      enabled: true
      branches:
        include:
          - main

stages:
- stage: qa
  displayName: qa
  jobs:
  - deployment: qa
    displayName: 'deploy helm chart on AKS qa'
    pool:
      vmImage: ubuntu-latest
    variables:
      k8sNamespace: $(projectName)-qa
      replicas: 1
    environment: qa-go-template
    strategy:
      runOnce:
        deploy:
          steps:
          - template: /common/cd-steps.yaml

    

    